baseurl = "https://www.hitfuturenow.com/"
title = "Brett Randall Taylor" 
name = "Brett Randall Taylor"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
#disqusShortname =  NULL
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-117328123-2"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Examples"
    url  = "/blog/"
    weight = 2

[[menu.main]]
    name = "Experience"
#    identifier = "faq"
    url  = "/faq/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 4

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/hitfuture"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "LinkedIn"
    url = "https://linkedin.com/in/brettrtaylor"
    pre = "<i class='fa fa-2x fa-linkedin'></i>" 

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com/hitfuture"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

#[[menu.topbar]]
#    weight = 4
#    name = "Email"
#    url = "mailto:info@hitfuturenow.com"
#    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Brett Randall Taylor"
    defaultKeywords = ["R" ,"RStudio" ,"Python" , "Data Science" ,"Healthcare" , "Leadership","Data Archiving"]
    defaultDescription = "HIT Data Now"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyB0PaVgTjOXPlrBt_LVxRZItFNgf2OQSio" 

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "info@hitfuturenow.com"

    about_us = "<p>Brett Taylor is focused on helping Healthcare organizations create a better experience for their patients by leveraging data.</p>"
    copyright = "Copyright (c) 2020, Brett Taylor; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/bretts_image001.jpg"
    address = """<p><strong>Brett R. Taylor</strong>
        <br>808 Carano Ct
        <br>Incline Village
        <br>Nevada, 89451
        <br>
        <strong>United States of America</strong>
      </p>
      """
    latitude = "39.257143"
    longitude = "-119.958766"
 
[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on LinkedIn or  info@hitfuturenow.com</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.
    title = "Skills"


[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Projects"
    subtitle = "I have been involved with many projects that adopt the right technology at the right time. There are some examples here."

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "We are ready to help you go to the next step."
    link_url = "/blog/"
    link_text = "Check out our blog posts"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Examples in Technology"
    subtitle = "Examples are shown on Blog Posts."
