---
title: HIT Future Now
author: Brett Taylor
date: '2018-04-30'
slug: hit-future-now
categories:
  - Business Opportunity
tags:
  - R
  - Python
  - Data
  - Management
banner: "img/bretts_image001.jpg"

---

```{r setup, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

I have wanted to make a blog post to describe how I think we can extend the power of the Healthcare Information Technology environment.  My focus has been on the development and the management of Healthcare I.T. since the late 1980's.  I have worked for several Health Systems, including Sutter Health, St. Luke's Idaho, Tahoe Forest as an employee and as a consultant, I have worked with dozen's of other Health Systems.  I have had many different experiences in the industry including Strategic Planning, EHR Software Development, Data Science and managing Infrastructure and Operations.   


I'm back in the consulting business now and I expect to be able to get as close as possible to the I.T. departments to enable their ability to adopt data analytics to improve their ability to deliver a good experience to the staff and others that deliver care.  I've focused on this in the past and I used analytics to make sure that we are focused in the right areas.  Healthcare IT needs to learn to innovate and to have a simple, stable, secure and sustainable environment.  I will share my opinions on how to move forward in H.I.T.

My future posts will have a variety of topics which will include:

* Business Opportunity in Healthcare I.T.
* Analytics in I.T.
* Dev/Ops
* Programming and Deploying the Language R
* Programming and Deploying Language Python
* Machine Learning and A.I.
* Data Management and Governance
* Using the Neo4j Graph Database to Analyze Healthcare


There are many reasons I want to start getting the blog posts up and running.   I do need to expose people to some of the analytics work and the tools that I'm using in our industry.  I prefer that our industry adopts solutions that are the best for your experience, and the best in cost.  I also want you to know that one of my main reasons to post to the blog is that since I'm working on a lot of different topics, I need a way to remember how I did this work.   Writing about it tends to allow me to look backward to remember I accomplished something in the past.   Yes, these blog posts are really all about me <i class="fa fa-user"></i>.
  You will see more posts and details in the areas above in the near future.

Thank you,      

Brett R. Taylor    
Consultant, __HIT Future Solutions, LLC__