---
title: "Perioperative Process"
author: "Brett Taylor"
date: '2018-07-18'
slug: perioperative-process
tags: Management
categories: Business Opportunity
---


## Phases

### Preoperative
The preoperative phase is used to perform tests, attempt to limit preoperational anxiety and may include the preoperative fasting.


### Perooperative

The peroperative period begins when the patient is transferred to the operating room table and ends with the transfer of a patient to the postanaesthesia care unit (PACU). During this period the patient is peroperatively monitored, anaesthetized, prepped, and draped, and the operation is performed. Nursing activities during this period focus on safety, infection prevention, and physiological response to peroperative anaesthesia. Peroperative radiation therapy and peroperative blood salvage may also be performed during this time.



### Postoperative

The postoperative period begins after the transfer to the Post Anesthesia Care Unit (PACU) and terminates with the resolution of the surgical sequelae. It is quite common for the very last of this period to end outside of the care of the surgical team. It is uncommon to provide extended care past the discharge of the patient from the PACU.